steps:

  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    id: Docker Build
    entrypoint: bash
    args:
      - -c
      - |
        echo $REPO_NAME
        echo $BRANCH_NAME
        echo $SHORT_SHA

        export build_registry=us-east1-docker.pkg.dev/project-lab-355520/tux-app/main

        docker build -t $build_registry:$SHORT_SHA .

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    id: Docker Push
    entrypoint: bash
    args:
      - -c
      - |
        docker push $build_registry:$SHORT_SHA

  # Altera manifesto Kubernetes para nova imagem criada
  - name: 'gcr.io/cloud-builders/docker'
    id: Update Kubernetes
    entrypoint: bash
    args:
      - -c
      - |

        git clone git@bitbucket.org:aristides-neto/tux-app-hml.git
        cd tux-app-hml
        echo "OLD:" && cat *-dp.yaml
        sed -i "s|\(.$build_registry:.*\)|\/$build_registry:$SHORT_SHA|g" *-dp.yaml
        echo && echo "NEW:" && cat *-dp.yaml
        git config --global user.email $build_service_account
        git config --global user.name "CloudBuildCICD"
        git add .
        git commit -a -m "Atualizado a imagem para a versao $SHORT_SHA"
        git push
