steps:

  # Environment
  - name: 'gcr.io/cloud-builders/docker'
    id: Environment
    entrypoint: bash
    args:
      - -c
      - |

        env
        set

    waitFor: []

  # Sonarqube Scanner
  - name: 'gcr.io/cloud-builders/docker'
    id: SonarQube Scanner
    entrypoint: bash
    args:
      - -c
      - |

        apt install -y jq

        docker run --rm \
          -e SONAR_HOST_URL=http://35.225.36.251 \
          -e SONAR_LOGIN=$$SONAR_LOGIN \
          -v "/workspace:/usr/src" \
          sonarsource/sonar-scanner-cli \
        -Dsonar.projectKey=$REPO_NAME \
        -Dsonar.sources=.

        export quality_gate_status=$(curl -s -u squ_ffe54c62ccea6dfcbcfd6867f619aea92fda8948: \
          http://35.225.36.251/api/qualitygates/project_status?projectKey=$REPO_NAME | jq '.projectStatus.status' | tr -d '"')

        if [ $quality_gate_status = 'OK' ]; then
          echo "SUCCESS: QUALITY GATE OK"
        else
          echo "ERROR: QUALITY GATE FAIL"
          exit 1
        fi;

    secretEnv: ['SONAR_LOGIN']
    waitFor: [Environment]

  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    id: Docker Build
    entrypoint: bash
    args:
      - -c
      - |

        docker build -t us-central1-docker.pkg.dev/images-2rpnet/$REPO_NAME/$BRANCH_NAME:$SHORT_SHA .
    waitFor: [SonarQube Scanner]

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    id: Docker Push
    entrypoint: bash
    args:
      - -c
      - |

        docker push us-central1-docker.pkg.dev/images-2rpnet/$REPO_NAME/$BRANCH_NAME:$SHORT_SHA
    waitFor: [Docker Build]

  

  # Altera manifesto Kubernetes para nova imagem criada
  - name: 'gcr.io/cloud-builders/docker'
    id: Update Kubernetes
    entrypoint: bash
    args:
      - -c
      - |
        
        git clone https://$$BITBUCKET_TOKEN@bitbucket.org/aristides-neto/tux-app-hml.git
        cd tux-app-hml
        echo "OLD:" && cat *-dp.yaml
        sed -i "s|\(.us-central1-docker.pkg.dev/images-2rpnet/$REPO_NAME/$BRANCH_NAME:.*\)| us-central1-docker.pkg.dev/images-2rpnet/$REPO_NAME/$BRANCH_NAME:$SHORT_SHA|g" *-dp.yaml
        echo && echo "NEW:" && cat *-dp.yaml
        git config --global user.email cgloud@pipeline.com
        git config --global user.name "CloudBuildCICD"
        git add .
        git commit -am "Atualizado a imagem para a versao $SHORT_SHA"
        git push
    secretEnv: ['BITBUCKET_TOKEN']
    waitFor: [Docker Push]

logsBucket: 'gs://cicd_logs'
# options:
#   logging: GCS_ONLY
availableSecrets:
  secretManager:
  - versionName: projects/466193647327/secrets/SONAR_LOGIN/versions/latest
    env: 'SONAR_LOGIN'
  - versionName: projects/466193647327/secrets/BITBUCKET_TOKEN/versions/latest
    env: 'BITBUCKET_TOKEN'